name: data_buffer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  image_picker: ^0.6.6+5
  flutter_icons: ^1.1.0
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^1.1.2
  syncfusion_flutter_datepicker: ^19.2.46
  cached_network_image: ^2.5.1
  grouped_buttons: ^1.0.4
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  table_calendar: ^3.0.1
  flutter_material_color_picker: ^1.0.5
  flex_color_picker: ^2.1.1
  toast: ^0.1.5
  flutter_colorpicker: ^0.5.0
  syncfusion_flutter_datagrid: ^19.2.49-beta
  flutter_gifimage: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/ic_imslogo.png
    - assets/images/googlelogo.png
    - assets/images/fblogo.jpg
    - assets/images/twitterlogo.jpg
    - assets/images/ulogo.png
    - assets/images/ulogo.jpg
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/icon_advice.png
    - assets/images/icon_calendar.jpg
    - assets/images/icon_data.png
    - assets/images/icon_hospital.png
    - assets/images/icon_new.png
    - assets/images/icon_recipe.png
    - assets/images/15_border.png
    - assets/images/20.png
    - assets/images/check.png
    - assets/images/cross.png
    - assets/images/icon_dentist.png
    - assets/images/icon_tooth.png
    - assets/images/icon_doctor.png
    - assets/images/drinkwater.gif
    - assets/images/icon_plan.png
    - assets/images/login_img.png
    - assets/images/baby_tooth.gif
    - assets/images/advice_bg.png
    - assets/images/advice_oral_hygiene.png
    - assets/images/advice_doctor.png
    - assets/images/advice_dentist.png
    - assets/images/footer.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
